### PR TITLE
build: use powerline for terminal prompt

### LINKED ISSUE #31: simplify command line
Some pod names can be very long which results in a very long command-line in the jupyterlab terminal. It should be shortened -- additionally, a tool like bash-it could be installed to make it a bit nicer to work with git in the shell.

### PR DESCRIPTION
**Pull request by rokroskar**
Prettifies the terminal shell with powerline. 

screenshot: 

image

closes #31

### CODE REVIEW

**Comment by rokroskar** [comment]
Thanks for testing @emmjab - btw, do you have powerline fonts installed on your computer already?

**Comment by rokroskar** [comment]
I resorted to using the "compatible" mode that results in an uglier font but the alternative is requiring that the user installs fonts on their system, which I think is a no-go.

**Comment by rokroskar** [comment]
I just changed all the image builds to use compatible mode and to not install any fonts. Please re-approve.

**Comment by emmjab** [comment]
> Thanks for testing @emmjab - btw, do you have powerline fonts installed on your computer already?

Nope!

> I just changed all the image builds to use compatible mode and to not install any fonts. Please re-approve.

Re-testing now.

Also I agree it would be nice to have a `common/` dir for dependencies that all the images share, in a following PR; so long as we make it clear what's going on in the docker file.

**Pull request merged**
